- name: task on conditions
  hosts: localhost
  vars:
      a: abc
  tasks:
    - name: condiiton on strings
      debug:
        msg: string condition is true
      when: a == "abc"
    - name: condition on strings1
      debug:
        msg: string condition is false
      when: a != "abc"
    - name: number1
      debug:
        msg: both numbers are equal
      when: b == 10

    - name: number2
      debug:
        msg: b is less than 20
      when:  b < 20

